class NestTry
{
	public static void main(String args[])
	{
		try
		{
		int a= args.length;
			//if no command line args are present,the following statement will generate a divide by zero exception
		int b=34 /a;

		System.out.println("a = "+a);
			try
			{
			if(a==1) 
				//if one command line args are present,then divide by zero exception will be  generated by following code.
			a=a/(a-a);
			
			if(a==2)
			{
				//if two command line args are present,then out of bound exception will be  generated by following code.
			int c[]={1};
			c[42] = 99;
			}
			}
			
			catch(ArrayIndexOutOfBoundsException e)
			{
			System.out.println("Array index oob:"+e);
			}
		}
			catch(ArithmeticException e)
			{
			System.out.println("Divide by 0:"+e);
			}
		}
	}
